server:
  port: 9897

spring:
  application:
    name: spring-boot-validation

  #MySQL Configuration
  datasource:
    url: jdbc:mysql://localhost:3307/microservices
    username: ${MYSQL_USER:nirmala}
    password: ${MYSQL_PASSWORD:nirmala@123}

    # HikariCP Connection Pool Configuration
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000

  #JPA Configuration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

# Logging Configuration
logging:
  level:
    #org.springframework.security: DEBUG
    com.sahu.springboot.security: DEBUG

# Swagger Configuration
springdoc:
  swagger-ui:
    path: /documentation
  api-docs:
    path: /api-docs

openapi:
  title: 🚀 Spring Boot Validation
  description: Spring Boot Validation using Spring boot validation starter and Global Exception Handler with @Valid and @Validated
  version: 1.0.0
  contact:
    name: Nirmala Sahu
    email: nirmalakumarsahu7@gmail.com
    url: https://nirmalakumarsahu.in
  servers:
    - name: dev
      url: http://localhost:9897
      description: Local Development URL

